// Generated by CoffeeScript 1.7.1
(function() {
  var demoText, getSeq, logoSettings, makeObj;

  demoText = ['HEXA'.split(''), 'FLIP'.split('')];

  makeObj = function(a) {
    var i, o, v, _i, _len;
    o = {};
    for (i = _i = 0, _len = a.length; _i < _len; i = ++_i) {
      v = a[i];
      o['letter' + i] = a;
    }
    return o;
  };

  document.addEventListener('DOMContentLoaded', function() {
    var action, hexaHorz, hexaVert, hexaBoth, i, logos, n, horzControls, vertControls, bothControls, textDemos, _fn, _i, _len, _ref;
    logos = document.getElementsByClassName('logo');
    textDemos = (function() {
      var _i, _results;
      _results = [];
      for (n = _i = 0; _i <= 1; n = ++_i) {
        _results.push(new HexaFlip(logos[n], makeObj(demoText[n]), logoSettings));
      }
      return _results;
    })();
    
    // Start flip left/right
    hexaHorz = new HexaFlip(document.getElementById('horz-demo'), {
      photos: (function() {
        var _i, _results;
        _results = [];
        
        //sets number of faces the cube will rotate through
        for (i = _i = 1; _i <= 4; i = ++_i) {
          _results.push("<iframe src='./cubeContent/" + i + ".html' height='200px' width='200px' frameborder=0'></iframe>");
        }
        return _results;
      })()
    }, {
      size: 200,
      horizontalFlip: true
    });
    horzControls = document.getElementById('horz-controls');
    _ref = ['flipBack', 'flip'];
    _fn = function(action) {
      return horzControls.children[i].addEventListener('click', (function() {
        return hexaHorz[action]();
      }), false);
    };
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      action = _ref[i];
      _fn(action);
    }
    // End flip left/right
    
    
  }, false);

}).call(this);

//# sourceMappingURL=demo.map